### ISSUE TITLE
Seriele communicatie hello world tussen LoRa module en arduino

### ISSUE THREAD

**Issue by Ethereal-Dev** [R2D2-2023/Binnenklimaat#10]
- [x] Seriele poorten aansluiten
- [x] Handmatig sensor data naar TTN versturen
- [x] Data van arduino naar Lopy sturen

**Comment by TheWezzz** [comment]
[] Seriele poorten aansluiten
[] Handmatig sensor data naar TTN versturen
[] Data van arduino naar Lopy sturen

**Comment by TheWezzz** [comment]
De draadjes zijn ongeveer 3 keer los en vast geweest, maar uiteindelijk lag het probleem bij de software van de lopy
